import React from "react";
import Head from "next/head";
import Image from "next/image";

const About = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <h1>Hello world!</h1>
      </main> */}
      <Head>
        <title>Marc Juan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="homePage">
        <div className="hero1">
          <div className="hero1Grid flex justify-evenly align-middle">
            <div className="flex flex-column justify-center">
              <h1>Hi, I'm Marc</h1>
              <h3>A Developer</h3>
            </div>
            <div className="flex justify-center align-middle">
              <div className="profilePicBorder">
                <img src="/Marc.png" className="profilePic" />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default About;
