import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marc Juan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="indexBg">
        <div className="hero1">
          {/* <b>Test</b> */}
          <div className="left">
            <div className="leftUp">
              <b className="text-white">leftUp</b>
            </div>
            <div className="leftDown">
              <b className="text-white">leftDown</b>
            </div>
          </div>
          <div className="right">
            <div className="rightContent">
              <div className="rchero1">
                <b className="text-white">leftDown</b>
              </div>
              <div className="rchero2">
                <b className="text-white">leftDown</b>
              </div>
            </div>
          </div>
        </div>
        <div className="footer2">
          <b className="text-white">Footer</b>
        </div>
      </main>
    </>
  );
}
