import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  GoHome,
  GoHomeFill,
  GoPerson,
  GoPersonFill,
  GoFileDirectory,
  GoFileDirectoryFill,
  GoMail,
} from "react-icons/go";
import {
  AiOutlineGithub,
  AiFillGithub,
  AiOutlineFacebook,
  AiFillFacebook,
  AiOutlineLinkedin,
  AiFillLinkedin,
  AiOutlineMail,
  AiFillMail,
} from "react-icons/ai";
import ProjectSwiper from "./projectSwiper";
import { TypeAnimation } from "react-type-animation";
import emailjs from "@emailjs/browser";
import SimpleSlider from "./reactSlick";
const content = [
  {
    id: 1,
    title: "Home",
    link: "home",
    icon: <GoHome />,
    iconActive: <GoHomeFill />,
  },
  {
    id: 2,
    title: "About Me",
    link: "about",
    icon: <GoPerson />,
    iconActive: <GoPersonFill />,
  },
  {
    id: 3,
    title: "Projects",
    link: "projects",
    icon: <GoFileDirectory />,
    iconActive: <GoFileDirectoryFill />,
  },
  // {
  //   id: 4,
  //   title: "Contacts",
  //   link: "contacts",
  //   icon: <GoMail />,
  //   iconActive: <GoMail />,
  // },
];

const MenuItem = ({ title, link, icon }) => {
  return (
    <Link href={`/#${link}`} passHref>
      <div className="sidebarIcons">{icon}</div>
    </Link>
  );
};

const skills = [
  {
    id: 1,
    title: "HTML",
    percentage: 95,
  },
  {
    id: 2,
    title: "CSS",
    percentage: 95,
  },
  {
    id: 3,
    title: "JavaScript",
    percentage: 80,
  },
  {
    id: 4,
    title: "React.js",
    percentage: 80,
  },
  {
    id: 5,
    title: "Node.js",
    percentage: 50,
  },
  {
    id: 6,
    title: "Next.js",
    percentage: 90,
  },
  {
    id: 7,
    title: "UI Design",
    percentage: 80,
  },
  {
    id: 8,
    title: "Figma",
    percentage: 90,
  },
];

const socials = [
  {
    id: 1,
    title: "Github",
    link: "https://github.com/Mac12880",
    icon: <AiOutlineGithub />,
    iconhover: <AiFillGithub />,
    color: "#6e5494",
  },
  {
    id: 2,
    title: "Facebook",
    link: "",
    icon: <AiOutlineFacebook />,
    iconhover: <AiFillFacebook />,
    color: "#4267B2",
  },
  {
    id: 3,
    title: "LinkedIn",
    link: "https://www.linkedin.com/in/marc-augustine-juan-b00b03237/",
    icon: <AiOutlineLinkedin />,
    iconhover: <AiFillLinkedin />,
    color: "#0077B5",
  },
  {
    id: 4,
    title: "Email",
    link: "#contacts",
    icon: <AiOutlineMail />,
    iconhover: <AiFillMail />,
    color: "#c71610",
  },
];
const SkillsItem = ({ title, percentage }) => {
  return (
    <div
      className="flex justify-center flex-row"
      style={{
        backgroundColor: "lightgray",
        width: "60%",
        height: "auto",
        marginTop: "5px",
        borderRadius: "1vw",
      }}
    >
      <div
        className="flex justify-center "
        style={{
          width: "20%",
          background: "lightgray",
          borderRadius: "1vw 0 0 1vw",
        }}
      >
        <p className="" style={{ fontSize: "1.8vw", color: "black" }}>
          {title}
        </p>
      </div>
      <div className="" style={{ width: "70%" }}>
        <div
          className=""
          style={{
            backgroundColor: "#efa00b",
            width: `${percentage}%`,
            borderRadius: "0.5vw 0.5vw 0.5vw 0.5vw",
          }}
        >
          <p
            className=""
            style={{ color: "#efa00b", fontSize: "1.8vw", textAlign: "left" }}
          >
            {percentage}%
          </p>
        </div>
      </div>
      <div className="flex justify-center" style={{ width: "10%" }}>
        <p className="" style={{ fontSize: "1.8vw" }}>
          {percentage}%
        </p>
      </div>
    </div>
  );
};

export default function Home() {
  const form = useRef();
  const sendEmail = (e) => {
    e.preventDefault();
    emailjs
      .sendForm(
        "service_cs9rcyz",
        "template_5s9ae0e",
        form.current,
        "9IIdycsS2IbbLhtZc"
      )
      .then(
        (result) => {
          console.log(result.text);
        },
        (error) => {
          console.log(error.text);
        }
      );
    e.target.reset();
  };
  return (
    <>
      <Head>
        <title>Marc Juan&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="indexBg">
        <div className="hero1">
          {/* <b>Test</b> */}
          <div className="left">
            <div className="leftContainer">
              {/* <div className="sidebarIcons">
                <GoHome />
              </div> */}
              {content.map((item) => {
                return <MenuItem {...item} key={item.id}></MenuItem>;
              })}
              <hr style={{ color: "white", width: "80%" }} />

              {socials.map((item) => {
                return (
                  <Link key={item.id} className="hover-button" href={item.link}>
                    {/* default */}
                    <span className="hover-button--off">
                      <div className="sidebarIcons">{item.icon}</div>
                    </span>
                    {/* hover */}
                    <span className="hover-button--on">
                      <div
                        className="sidebarIcons"
                        style={{ color: `${item.color}` }}
                      >
                        {item.iconhover}
                      </div>
                    </span>
                  </Link>
                );
              })}
            </div>
          </div>
          <div className="right dark">
            <div className="rightHeader">
              <div className="rcHeader">
                <div className="rcHeaderIcon">
                  <Link href="/" passHref>
                    <GoHome />
                  </Link>
                </div>
                <div className="rcHeaderButton">
                  <p>Resume</p>
                </div>
              </div>
            </div>
            <div className="rightContent">
              {/* <div className="rcHeader">
                <div className="rcHeaderIcon">
                  <GoHome />
                </div>
                <div className="rcHeaderButton">
                  <p>Resume</p>
                </div>
              </div> */}
              <section className="rchero1">
                <div className="rchero1left">
                  <img
                    className="profilePic"
                    src="mjuanpic.png"
                    alt="Profile pic"
                  />
                </div>
                <div className="rchero1right" id="home">
                  {/* <b className="hero1Header">Web Developer</b> */}
                  <TypeAnimation
                    className="hero1Header"
                    sequence={[`I'm a Developer and a Designer.`, 1000, ""]}
                    speed={50}
                    style={{ whiteSpace: "normal", fontWeight: "bold" }}
                    repeat={Infinity}
                  />
                  <b className="hero1SubHeader">Marc Augustine R. Juan</b>
                  <p className="hero1Paragraph">
                    I am seeking an opportunity in software development as a
                    front-end web developer or full-stack developer, where I can
                    apply my theoretical knowledge to real-world projects,
                    enhance my technical skills, and gain valuable experience
                    while working in a collaborative team environment.
                  </p>
                </div>
              </section>
              <section className="rchero2" id="about">
                <div className="flex justify-center" style={{ width: "100%" }}>
                  <div
                    className="flex justify-center"
                    style={{ width: "9vw", borderBottom: "1px solid white" }}
                  >
                    <b className="text-white" style={{ fontSize: "3vw" }}>
                      About
                    </b>
                  </div>
                </div>

                <div className="flex justify-center">
                  <p className="rcHero2AboutMe text-white">
                    Hi, I&apos;m Marc. I have completed my internship and am now
                    embarking on my freelance journey as either a front-end web
                    developer or a full-stack developer. I&apos;ve already
                    undertaken projects using Next.js and React.js,
                    collaborating with talented individuals to craft digital
                    products for both businesses and consumers. I am confident
                    in my skills and design abilities, naturally curious, and
                    continually refining my technical and design skills.
                  </p>
                </div>

                <div className="flex justify-center" style={{ width: "100%" }}>
                  <div
                    className="flex justify-center"
                    style={{ width: "7.1vw", borderBottom: "1px solid white" }}
                  >
                    <b className="text-white" style={{ fontSize: "3vw" }}>
                      Skills
                    </b>
                  </div>
                </div>
                <div
                  className="flex justify-center items-center flex-col"
                  style={{
                    paddingTop: "1vw",
                    paddingBottom: "1vw",
                  }}
                >
                  {skills.map((item) => {
                    return <SkillsItem {...item} key={item.id}></SkillsItem>;
                  })}
                </div>

                <section id="projects">
                  <div
                    className="flex justify-center items-center flex-col"
                    style={{
                      width: "90vw",
                      marginTop: "5vw",
                      // height: "50vw",
                    }}
                  >
                    <div
                      className="flex justify-center"
                      style={{ width: "11vw", borderBottom: "1px solid white" }}
                    >
                      <b className="text-white" style={{ fontSize: "3vw" }}>
                        Projects
                      </b>
                    </div>
                    <div
                      style={{
                        width: "90%",
                        marginTop: "1vw",
                        marginBottom: "1vw",
                        height: "100%",
                      }}
                    >
                      {/* <ProjectSwiper /> */}
                      <SimpleSlider />
                    </div>
                  </div>
                  <div className="flex justify-center"></div>
                </section>

                <section
                  id="contacts"
                  className="flex justify-center items-center "
                >
                  <div className="flex justify-center items-center w-11/12 mt-60 h-full p-4 my-8 bg-white border border-gray-200 rounded-lg shadow-md sm:p-6 lg:p-8 dark:bg-gray-800 dark:border-white">
                    {/* left */}
                    <div className="flex flex-col w-2/4 text-white items-center content-between h-1/2">
                      <div className="flex justify-center items-start w-full ">
                        <b style={{ fontSize: "3vw" }}>Contact Me</b>
                      </div>

                      <div className="flex justify-evenly items-end w-3/4 h-1/2">
                        {...socials.map((item) => {
                          if (item.title === "Email") {
                            return;
                          } else {
                            return (
                              <Link
                                key={item.id}
                                className="hover-button"
                                href={item.link}
                              >
                                {/* default */}
                                <span className="hover-button--off">
                                  <div
                                    className="sidebarIcons"
                                    // style={{ fontSize: "2vw" }}
                                  >
                                    {item.icon}
                                  </div>
                                </span>
                                {/* hover */}
                                <span className="hover-button--on">
                                  <div
                                    className="sidebarIcons"
                                    style={{ color: `${item.color}` }}
                                  >
                                    {item.iconhover}
                                  </div>
                                </span>
                              </Link>
                            );
                          }
                        })}
                      </div>
                    </div>
                    {/* right */}
                    <div className="flex justify-center items-center flex-col w-2/4">
                      <form
                        ref={form}
                        onSubmit={sendEmail}
                        className="flex justify-center items-center flex-col w-full pt-6 pb-6"
                      >
                        {/* Name */}
                        <div className=" relative z-0 mb-5 w-3/4">
                          <input
                            type="text"
                            id="floating_standard_name"
                            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-white dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                            placeholder=" "
                            name="name_from"
                          />
                          <label
                            htmlFor="floating_standard_name"
                            className="absolute text-sm text-gray-500 dark:text-white duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                          >
                            Name
                          </label>
                        </div>
                        {/* email */}
                        <div className=" relative z-0 mb-5 w-3/4">
                          <input
                            type="email"
                            id="floating_standard_email"
                            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-white dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                            placeholder=" "
                            name="email_from"
                          />
                          <label
                            htmlFor="floating_standard_email"
                            className="absolute text-sm text-gray-500 dark:text-white duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                          >
                            Email
                          </label>
                        </div>
                        {/* Subject */}
                        <div className=" relative z-0 mb-5 w-3/4">
                          <input
                            type="text"
                            id="floating_standard_subject"
                            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-white dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                            placeholder=" "
                            name="subject_from"
                          />
                          <label
                            htmlFor="floating_standard_subject"
                            className="absolute text-sm text-gray-500 dark:text-white duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                          >
                            Subject
                          </label>
                        </div>

                        {/* message */}
                        <div className=" relative z-0 mb-5 w-3/4">
                          <textarea
                            type="email"
                            id="floating_standard_message"
                            className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-white dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer "
                            placeholder=" "
                            name="message_from"
                            style={{ minHeight: "50px" }}
                          />
                          <label
                            htmlFor="floating_standard_message"
                            className="absolute text-sm text-gray-500 dark:text-white duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                          >
                            Message
                          </label>
                        </div>
                        <div className="relative z-0 ">
                          <button
                            type="submit"
                            className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                            style={{ width: "100%" }}
                          >
                            Send
                          </button>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div className="flex justify-center items-center"></div>
                </section>
              </section>
            </div>
          </div>
        </div>
        <div className="footer2">
          <b className="text-white">MARC JUAN</b>
          <b className="" style={{ marginLeft: "0.5vw", color: "orange" }}>
            ©2023
          </b>
        </div>
      </main>
    </>
  );
}
