import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marc Juan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="indexBg">
        <div className="hero1">
          {/* <b>Test</b> */}
          <div className="left">
            <div className="leftUp">
              <b className="text-white">leftUp</b>
            </div>
            <div className="leftDown">
              <b className="text-white">leftDown</b>
            </div>
          </div>
          <div className="right">
            <div className="rightContent">
              <div className="rchero1">
                <div className="rchero1left">
                  <img
                    className="profilePic"
                    src="mjuanpic.png"
                    alt="Profile pic"
                  />
                </div>
                <div className="rchero1right">
                  <b className="hero1Header">Web Developer</b>
                  <b className="hero1SubHeader">Marc Augustine R. Juan</b>
                  <p className="hero1Paragraph">
                    Looking for an internship opportunity in software
                    development as a front-end web developer or full-stack
                    developer, where I can apply my theoretical knowledge to
                    real-world projects, enhance my technical skills, and gain
                    valuable experience working in a collaborative team
                    environment
                  </p>
                </div>
              </div>
              <div className="rchero2">
                <b className="text-white">leftDown</b>
              </div>
            </div>
          </div>
        </div>
        <div className="footer2">
          <b className="text-white">Footer</b>
        </div>
      </main>
    </>
  );
}
